version: '3.0'

services:
  db:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5001:5432"

  app:
    build: ./app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5003:5003"
    