version: '3.8'

services:
  db:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5001:5432"
    networks:
      - my_network

  app:
    build: ./app
    env_file:
      - .env
    ports:
      - "5002:5002"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge